### PR TITLE
Restart with MCU enabled functionnality implementation

### PR DESCRIPTION
**Pull request by JulienMuzeau**

### CODE REVIEW

**Comment by johache** [comment]
I'm not going to be the one to review your PR, but a description would be nice :)

**Comment by letchoo** [comment]
Looks good so far. I'll implement the changes as proposed by @tienthanh8490 after merging.

**Comment by tienthanh8490** [comment]
@letchoo you can checkout Julien's branch and add the changes first, then we can merge

**Comment by letchoo** [comment]
Merged with #126

**Pull request closed without merging**
