### PR TITLE
ESS-434: Reconnection should use WebRTC way of re-negotiation

### PR DESCRIPTION
**Pull request by letchoo**
!! Please do review but do not merge

__Fixes should contain:__
- [JIRA Ticket ESS-434](http://jira.temasys.com.sg/browse/ESS-434) - Revamp on reconnection method. Instead of destroying and re-creating new RTCPeerConnection objects, use the same RTCPeerConnection objects and do re-establishment of connection using Offer / Answer.

__Things to double-check and take note:__
- When ICE connection fails to established (after O / A), do not touch anything but let the browser handle any restart of ICE connections.
- When replacing stream or restarting a connection without stream, use reconnection with O / A again.
- Implemented polyfill for `RTCPeerConnection.removeStream` to remove all tracks from the RTCPeerConnection object in Firefox browsers.

This is the version of ~~0.6.5~~ 0.6.6 development changes that was tested before in demos

### CODE REVIEW

**Comment by letchoo** [comment]
__Changes to take note of:__
- If it's a restart mechanism, offer Sdp will be in the the RESTART message. If the message is empty or `null`, it means that the other party has to do re-negotiation
- Added checks in message handlers make sure that the handshaking steps are followed accordingly. If in `_offerHandler`, it should be in `"stable"` state in order to add remote offer sdp. If in `_answerHandler`, it should should be in `"have-local-offer"` state in order to add remote answer sdp.
- Added checks in `_restartPeerConnection` to make sure that the state is `"stable"` first before re-negotiation can be made, or else send the current existing localDescription to the other party. This can be ignored in the message handlers.
- Timers are still kept, but it conforms to the re-negotiation methods.
- Added a new variable `_peerRenegoCallbacks` that `_restartPeerConnection` can hook events to instead of using `_trigger` for internal events. This will leverage us in trickleICE ON / OFF use-cases.
- Removed checks that if remoteDescription is set, ignore, in `_offerHandler`, `_answerHandler` and localDescription for `_setLocalDescription`.

__Things to double check:__
- The handled logic of `_peerRenegoCallbacks` if there could be some form of steps that goes out of order.
- What happens with MCU use-case?
- What happens with android sdk / ios sdk use-case?
- . etc more..

**Comment by letchoo** [comment]
@tienthanh8490 please review. please do commit to this branch if required.

**Comment by letchoo** [comment]
!! ALERT !! - Trickle ICE OFF seems to be having issues with reconnectivity. To be fixed.

**Comment by tienthanh8490** [comment]
@letchoo 
1/ Which items in the double check list were done, which ones were left ? 
2/ Can you give more details on the hanging issue with screensharing plugin ?
3/ What was the issue with trickle ice off just now ? We should not ignore that just because it randomly worked
4/ How are you handling the simultaneous refresh connection invoked from both sides ?
5/ Why rollback socket.io 1.3.7 to 1.3.5 ?

**Comment by letchoo** [comment]
@tienthanh8490 
1. So far, all the use-cases I can think of is done. Please do add.
2. When safari / IE starts screensharing, the screensharing stream is reflected on the other peer's end. But stopping it results in the connection hanging.
3. It seems that the reconnectivity takes like about 2-3 times before connection is established. Seems like in the "failure" case, the last `RTCIceCandidate.candidate` is not empty or `null`.
4. I thought it of a way to drop and add sdps when required based off the `_offerHandler` and `_answerHandler` and `_restartPeerConnection`. I checked with states instead. We can conduct tests to ensure how it works and the logic in some ways.
5. That's before we had the idea of socket.io 1.3.7 upgrade :) hence I had to rollback not to destroy the previous version 1.3.5 when updating

**Comment by tienthanh8490** [comment]
I got multiple error on first connection (no restart involved):

```
SkylinkJS [QxrQiYxWmiB445SOABeq] - <<RTCPeerConnection>> Failed re-sending localDescription as there is no localDescription set to connection. There could be a handshaking step error Object {localDescription: RTCSessionDescription, remoteDescription: RTCSessionDescription}
```

```
Uncaught TypeError: Failed to execute 'createAnswer' on 'RTCPeerConnection': Malformed constraints object.
```

Connection is never complete because offer/answer keeps failing

**Comment by letchoo** [comment]
@tienthanh8490 Thanks. Where (platform) did you test on?

**Comment by tienthanh8490** [comment]
Both Chrome 48

**Comment by letchoo** [comment]
@tienthanh8490 Ok noted. I guess for now I should remove the `iceRestart: true` of `RTCAnswerOptions` for `createAnswer`.

**Comment by letchoo** [comment]
@tienthanh8490 Please do also expand the object for the `RTCSessionDescription` as well if possible. That's because chrome automatically defines it but without the sdp. 
`RTCSessionDescription { type: "", sdp: ""}`
You can try constructing a new RTCPeerConnection object in the console to see it.

**Comment by letchoo** [comment]
@tienthanh8490 Please test again with the new changes

**Comment by tienthanh8490** [comment]
First connection works now but invoking refreshConnection gives this error

```
SkylinkJS [Ubt3u6gqoI01-iMJABgd] - (offer) Failed setting remote description: Failed to set remote offer sdp: Called in wrong state: STATE_SENTOFFER
```

Where would you expand the RTCSessionDescription object ? Why don't just let adapterJS handle it ?

**Comment by letchoo** [comment]
@tienthanh8490 Expand as in the console log when you post the results :)

```
SkylinkJS [ONKHA0T8yUl9hjhSABg2] - <<RTCIceCandidate>> Ice candidate generated -> RTCIceCandidate {}candidate: "candidate:83764836 2 udp 8331006 172.31.27.222 56616 typ relay raddr 219.74.68.248 rport 57435 generation 0"sdpMLineIndex: 0sdpMid: "audio"__proto__: RTCIceCandidate
```

So I can see the details of the object inside it.

**Comment by tienthanh8490** [comment]
Ok these are more details

```
SkylinkJS [HBeWmGbm0MJf3cLRABg_] - Sending to peer -> Object {type: "offer", sdp: "v=0
↵o=- 6079183416895985087 3 IN IP4 127.0.0.1
↵s…id:data
↵a=sctpmap:5000 webrtc-datachannel 1024
↵", mid: "9WjKwLA6MwHaLx43ABg-", target: "HBeWmGbm0MJf3cLRABg_", rid: "7526ffcc-9be1-43eb-93fa-315f8f353aaa_api_df"…}mid: "9WjKwLA6MwHaLx43ABg-"resend: truerid: "7526ffcc-9be1-43eb-93fa-315f8f353aaa_api_df"sdp: "v=0
↵o=- 6079183416895985087 3 IN IP4 127.0.0.1
↵s=-
↵t=0 0
↵a=group:BUNDLE audio video data
↵a=msid-semantic: WMS WWFY9RX4Wr2bVANog8GozuPOk8NDmHtfHZA1
↵m=audio 59080 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
↵c=IN IP4 118.189.54.34
↵b=AS:50
↵a=rtcp:9 IN IP4 0.0.0.0
↵a=candidate:3191242573 1 udp 2122260223 192.168.1.51 59080 typ host generation 0
↵a=candidate:1210451609 1 udp 1686052607 118.189.54.34 59080 typ srflx raddr 192.168.1.51 rport 59080 generation 0
↵a=ice-ufrag:LimJjQ0blGVkTeqA
↵a=ice-pwd:iKShv2/+SCKL/1T4sXzdaS3w
↵a=fingerprint:sha-256 65:46:C0:16:7B:5D:09:02:AE:E3:6A:BE:A1:80:57:A8:E8:92:6D:D7:A6:ED:DE:3C:3D:DD:7C:8C:FB:6C:04:58
↵a=setup:actpass
↵a=mid:audio
↵a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
↵a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
↵a=sendrecv
↵a=rtcp-mux
↵a=rtpmap:111 opus/48000/2
↵a=fmtp:111 minptime=10; stereo=1; useinbandfec=1
↵a=rtpmap:103 ISAC/16000
↵a=rtpmap:104 ISAC/32000
↵a=rtpmap:9 G722/8000
↵a=rtpmap:0 PCMU/8000
↵a=rtpmap:8 PCMA/8000
↵a=rtpmap:106 CN/32000
↵a=rtpmap:105 CN/16000
↵a=rtpmap:13 CN/8000
↵a=rtpmap:126 telephone-event/8000
↵a=maxptime:60
↵a=ssrc:1956913283 cname:2t/rBbqdLQmWhB4D
↵a=ssrc:1956913283 msid:WWFY9RX4Wr2bVANog8GozuPOk8NDmHtfHZA1 2eeea80a-76ad-44dc-8786-5b93e35d03f6
↵a=ssrc:1956913283 mslabel:WWFY9RX4Wr2bVANog8GozuPOk8NDmHtfHZA1
↵a=ssrc:1956913283 label:2eeea80a-76ad-44dc-8786-5b93e35d03f6
↵m=video 9 UDP/TLS/RTP/SAVPF 100 101 116 117 96
↵c=IN IP4 0.0.0.0
↵b=AS:256
↵a=rtcp:9 IN IP4 0.0.0.0
↵a=ice-ufrag:LimJjQ0blGVkTeqA
↵a=ice-pwd:iKShv2/+SCKL/1T4sXzdaS3w
↵a=fingerprint:sha-256 65:46:C0:16:7B:5D:09:02:AE:E3:6A:BE:A1:80:57:A8:E8:92:6D:D7:A6:ED:DE:3C:3D:DD:7C:8C:FB:6C:04:58
↵a=setup:actpass
↵a=mid:video
↵a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
↵a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
↵a=extmap:4 urn:3gpp:video-orientation
↵a=sendrecv
↵a=rtcp-mux
↵a=rtpmap:100 VP8/90000
↵a=rtcp-fb:100 ccm fir
↵a=rtcp-fb:100 nack
↵a=rtcp-fb:100 nack pli
↵a=rtcp-fb:100 goog-remb
↵a=rtpmap:101 VP9/90000
↵a=rtcp-fb:101 ccm fir
↵a=rtcp-fb:101 nack
↵a=rtcp-fb:101 nack pli
↵a=rtcp-fb:101 goog-remb
↵a=rtpmap:116 red/90000
↵a=rtpmap:117 ulpfec/90000
↵a=rtpmap:96 rtx/90000
↵a=fmtp:96 apt=100
↵a=ssrc-group:FID 2921039801 1022672387
↵a=ssrc:2921039801 cname:2t/rBbqdLQmWhB4D
↵a=ssrc:2921039801 msid:WWFY9RX4Wr2bVANog8GozuPOk8NDmHtfHZA1 501d2e33-717c-41e0-971e-d5c6f45a5b9d
↵a=ssrc:2921039801 mslabel:WWFY9RX4Wr2bVANog8GozuPOk8NDmHtfHZA1
↵a=ssrc:2921039801 label:501d2e33-717c-41e0-971e-d5c6f45a5b9d
↵a=ssrc:1022672387 cname:2t/rBbqdLQmWhB4D
↵a=ssrc:1022672387 msid:WWFY9RX4Wr2bVANog8GozuPOk8NDmHtfHZA1 501d2e33-717c-41e0-971e-d5c6f45a5b9d
↵a=ssrc:1022672387 mslabel:WWFY9RX4Wr2bVANog8GozuPOk8NDmHtfHZA1
↵a=ssrc:1022672387 label:501d2e33-717c-41e0-971e-d5c6f45a5b9d
↵m=application 9 DTLS/SCTP 5000
↵c=IN IP4 0.0.0.0
↵b=AS:1638400
↵a=ice-ufrag:LimJjQ0blGVkTeqA
↵a=ice-pwd:iKShv2/+SCKL/1T4sXzdaS3w
↵a=fingerprint:sha-256 65:46:C0:16:7B:5D:09:02:AE:E3:6A:BE:A1:80:57:A8:E8:92:6D:D7:A6:ED:DE:3C:3D:DD:7C:8C:FB:6C:04:58
↵a=setup:actpass
↵a=mid:data
↵a=sctpmap:5000 webrtc-datachannel 1024
↵"target: "HBeWmGbm0MJf3cLRABg_"type: "offer"__proto__: Object
skylink.complete.js:16417 SkylinkJS - <<Socket>> Received message
skylink.complete.js:16417 SkylinkJS - <<Event>> (channelMessage) Event is fired
skylink.complete.js:16417 SkylinkJS - <<Event>> (channelMessage) Event is triggered
skylink.complete.js:16415 SkylinkJS [HBeWmGbm0MJf3cLRABg_] - Received from peer -> offer
skylink.complete.js:16415 SkylinkJS [HBeWmGbm0MJf3cLRABg_] - (offer) Received offer from peer. Session description: v=0
o=- 3319445162480130602 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video data
a=msid-semantic: WMS ip2TeC0zRQU9NTxb5wUvWvXNaRqfw4OBJauw
m=audio 64747 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
c=IN IP4 118.189.54.34
b=AS:50
a=rtcp:56065 IN IP4 118.189.54.34
a=candidate:3191242573 1 udp 2122260223 192.168.1.51 64747 typ host generation 0
a=candidate:3191242573 2 udp 2122260222 192.168.1.51 56065 typ host generation 0
a=candidate:1210451609 1 udp 1686052607 118.189.54.34 64747 typ srflx raddr 192.168.1.51 rport 64747 generation 0
a=candidate:1210451609 2 udp 1686052606 118.189.54.34 56065 typ srflx raddr 192.168.1.51 rport 56065 generation 0
a=candidate:4038427581 1 tcp 1518280447 192.168.1.51 0 typ host tcptype active generation 0
a=candidate:4038427581 2 tcp 1518280446 192.168.1.51 0 typ host tcptype active generation 0
a=ice-ufrag:Go2bBoWAFVSF8R7B
a=ice-pwd:u7zcCfcuUv1Z4PSMm6xwoO/b
a=fingerprint:sha-256 65:46:C0:16:7B:5D:09:02:AE:E3:6A:BE:A1:80:57:A8:E8:92:6D:D7:A6:ED:DE:3C:3D:DD:7C:8C:FB:6C:04:58
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; stereo=1; useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:3914187334 cname:KfVGhc3mWsN8fRic
a=ssrc:3914187334 msid:ip2TeC0zRQU9NTxb5wUvWvXNaRqfw4OBJauw 6496e4e2-6e0b-4ffe-931b-48cb458a04e9
a=ssrc:3914187334 mslabel:ip2TeC0zRQU9NTxb5wUvWvXNaRqfw4OBJauw
a=ssrc:3914187334 label:6496e4e2-6e0b-4ffe-931b-48cb458a04e9
m=video 53522 UDP/TLS/RTP/SAVPF 100 101 116 117 96
c=IN IP4 118.189.54.34
b=AS:256
a=rtcp:58281 IN IP4 118.189.54.34
a=candidate:3191242573 1 udp 2122260223 192.168.1.51 53522 typ host generation 0
a=candidate:3191242573 2 udp 2122260222 192.168.1.51 58281 typ host generation 0
a=candidate:1210451609 1 udp 1686052607 118.189.54.34 53522 typ srflx raddr 192.168.1.51 rport 53522 generation 0
a=candidate:1210451609 2 udp 1686052606 118.189.54.34 58281 typ srflx raddr 192.168.1.51 rport 58281 generation 0
a=candidate:4038427581 1 tcp 1518280447 192.168.1.51 0 typ host tcptype active generation 0
a=candidate:4038427581 2 tcp 1518280446 192.168.1.51 0 typ host tcptype active generation 0
a=ice-ufrag:Go2bBoWAFVSF8R7B
a=ice-pwd:u7zcCfcuUv1Z4PSMm6xwoO/b
a=fingerprint:sha-256 65:46:C0:16:7B:5D:09:02:AE:E3:6A:BE:A1:80:57:A8:E8:92:6D:D7:A6:ED:DE:3C:3D:DD:7C:8C:FB:6C:04:58
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=sendrecv
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtpmap:101 VP9/90000
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=ssrc-group:FID 3151320459 4015668215
a=ssrc:3151320459 cname:KfVGhc3mWsN8fRic
a=ssrc:3151320459 msid:ip2TeC0zRQU9NTxb5wUvWvXNaRqfw4OBJauw 19b2e515-2ee1-45f1-b559-f5eac9575429
a=ssrc:3151320459 mslabel:ip2TeC0zRQU9NTxb5wUvWvXNaRqfw4OBJauw
a=ssrc:3151320459 label:19b2e515-2ee1-45f1-b559-f5eac9575429
a=ssrc:4015668215 cname:KfVGhc3mWsN8fRic
a=ssrc:4015668215 msid:ip2TeC0zRQU9NTxb5wUvWvXNaRqfw4OBJauw 19b2e515-2ee1-45f1-b559-f5eac9575429
a=ssrc:4015668215 mslabel:ip2TeC0zRQU9NTxb5wUvWvXNaRqfw4OBJauw
a=ssrc:4015668215 label:19b2e515-2ee1-45f1-b559-f5eac9575429
m=application 54667 DTLS/SCTP 5000
c=IN IP4 118.189.54.34
b=AS:1638400
a=candidate:3191242573 1 udp 2122260223 192.168.1.51 54667 typ host generation 0
a=candidate:1210451609 1 udp 1686052607 118.189.54.34 54667 typ srflx raddr 192.168.1.51 rport 54667 generation 0
a=candidate:4038427581 1 tcp 1518280447 192.168.1.51 0 typ host tcptype active generation 0
a=ice-ufrag:Go2bBoWAFVSF8R7B
a=ice-pwd:u7zcCfcuUv1Z4PSMm6xwoO/b
a=fingerprint:sha-256 65:46:C0:16:7B:5D:09:02:AE:E3:6A:BE:A1:80:57:A8:E8:92:6D:D7:A6:ED:DE:3C:3D:DD:7C:8C:FB:6C:04:58
a=setup:actpass
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024

skylink.complete.js:16417 SkylinkJS - <<Event>> (handshakeProgress) Event is fired
skylink.complete.js:16417 SkylinkJS - <<Event>> (handshakeProgress) Event is triggered
skylink.complete.js:16415 SkylinkJS [HBeWmGbm0MJf3cLRABg_] - <<RTCSessionDescription>> (offer) Session description object created RTCSessionDescription {}sdp: "v=0
↵o=- 3319445162480130602 3 IN IP4 127.0.0.1
↵s=-
↵t=0 0
↵a=group:BUNDLE audio video data
↵a=msid-semantic: WMS ip2TeC0zRQU9NTxb5wUvWvXNaRqfw4OBJauw
↵m=audio 64747 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
↵c=IN IP4 118.189.54.34
↵b=AS:50
↵a=rtcp:56065 IN IP4 118.189.54.34
↵a=candidate:3191242573 1 udp 2122260223 192.168.1.51 64747 typ host generation 0
↵a=candidate:3191242573 2 udp 2122260222 192.168.1.51 56065 typ host generation 0
↵a=candidate:1210451609 1 udp 1686052607 118.189.54.34 64747 typ srflx raddr 192.168.1.51 rport 64747 generation 0
↵a=candidate:1210451609 2 udp 1686052606 118.189.54.34 56065 typ srflx raddr 192.168.1.51 rport 56065 generation 0
↵a=candidate:4038427581 1 tcp 1518280447 192.168.1.51 0 typ host tcptype active generation 0
↵a=candidate:4038427581 2 tcp 1518280446 192.168.1.51 0 typ host tcptype active generation 0
↵a=ice-ufrag:Go2bBoWAFVSF8R7B
↵a=ice-pwd:u7zcCfcuUv1Z4PSMm6xwoO/b
↵a=fingerprint:sha-256 65:46:C0:16:7B:5D:09:02:AE:E3:6A:BE:A1:80:57:A8:E8:92:6D:D7:A6:ED:DE:3C:3D:DD:7C:8C:FB:6C:04:58
↵a=setup:actpass
↵a=mid:audio
↵a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
↵a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
↵a=sendrecv
↵a=rtcp-mux
↵a=rtpmap:111 opus/48000/2
↵a=fmtp:111 minptime=10; stereo=1; useinbandfec=1
↵a=rtpmap:103 ISAC/16000
↵a=rtpmap:104 ISAC/32000
↵a=rtpmap:9 G722/8000
↵a=rtpmap:0 PCMU/8000
↵a=rtpmap:8 PCMA/8000
↵a=rtpmap:106 CN/32000
↵a=rtpmap:105 CN/16000
↵a=rtpmap:13 CN/8000
↵a=rtpmap:126 telephone-event/8000
↵a=maxptime:60
↵a=ssrc:3914187334 cname:KfVGhc3mWsN8fRic
↵a=ssrc:3914187334 msid:ip2TeC0zRQU9NTxb5wUvWvXNaRqfw4OBJauw 6496e4e2-6e0b-4ffe-931b-48cb458a04e9
↵a=ssrc:3914187334 mslabel:ip2TeC0zRQU9NTxb5wUvWvXNaRqfw4OBJauw
↵a=ssrc:3914187334 label:6496e4e2-6e0b-4ffe-931b-48cb458a04e9
↵m=video 53522 UDP/TLS/RTP/SAVPF 100 101 116 117 96
↵c=IN IP4 118.189.54.34
↵b=AS:256
↵a=rtcp:58281 IN IP4 118.189.54.34
↵a=candidate:3191242573 1 udp 2122260223 192.168.1.51 53522 typ host generation 0
↵a=candidate:3191242573 2 udp 2122260222 192.168.1.51 58281 typ host generation 0
↵a=candidate:1210451609 1 udp 1686052607 118.189.54.34 53522 typ srflx raddr 192.168.1.51 rport 53522 generation 0
↵a=candidate:1210451609 2 udp 1686052606 118.189.54.34 58281 typ srflx raddr 192.168.1.51 rport 58281 generation 0
↵a=candidate:4038427581 1 tcp 1518280447 192.168.1.51 0 typ host tcptype active generation 0
↵a=candidate:4038427581 2 tcp 1518280446 192.168.1.51 0 typ host tcptype active generation 0
↵a=ice-ufrag:Go2bBoWAFVSF8R7B
↵a=ice-pwd:u7zcCfcuUv1Z4PSMm6xwoO/b
↵a=fingerprint:sha-256 65:46:C0:16:7B:5D:09:02:AE:E3:6A:BE:A1:80:57:A8:E8:92:6D:D7:A6:ED:DE:3C:3D:DD:7C:8C:FB:6C:04:58
↵a=setup:actpass
↵a=mid:video
↵a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
↵a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
↵a=extmap:4 urn:3gpp:video-orientation
↵a=sendrecv
↵a=rtcp-mux
↵a=rtpmap:100 VP8/90000
↵a=rtcp-fb:100 ccm fir
↵a=rtcp-fb:100 nack
↵a=rtcp-fb:100 nack pli
↵a=rtcp-fb:100 goog-remb
↵a=rtpmap:101 VP9/90000
↵a=rtcp-fb:101 ccm fir
↵a=rtcp-fb:101 nack
↵a=rtcp-fb:101 nack pli
↵a=rtcp-fb:101 goog-remb
↵a=rtpmap:116 red/90000
↵a=rtpmap:117 ulpfec/90000
↵a=rtpmap:96 rtx/90000
↵a=fmtp:96 apt=100
↵a=ssrc-group:FID 3151320459 4015668215
↵a=ssrc:3151320459 cname:KfVGhc3mWsN8fRic
↵a=ssrc:3151320459 msid:ip2TeC0zRQU9NTxb5wUvWvXNaRqfw4OBJauw 19b2e515-2ee1-45f1-b559-f5eac9575429
↵a=ssrc:3151320459 mslabel:ip2TeC0zRQU9NTxb5wUvWvXNaRqfw4OBJauw
↵a=ssrc:3151320459 label:19b2e515-2ee1-45f1-b559-f5eac9575429
↵a=ssrc:4015668215 cname:KfVGhc3mWsN8fRic
↵a=ssrc:4015668215 msid:ip2TeC0zRQU9NTxb5wUvWvXNaRqfw4OBJauw 19b2e515-2ee1-45f1-b559-f5eac9575429
↵a=ssrc:4015668215 mslabel:ip2TeC0zRQU9NTxb5wUvWvXNaRqfw4OBJauw
↵a=ssrc:4015668215 label:19b2e515-2ee1-45f1-b559-f5eac9575429
↵m=application 54667 DTLS/SCTP 5000
↵c=IN IP4 118.189.54.34
↵b=AS:1638400
↵a=candidate:3191242573 1 udp 2122260223 192.168.1.51 54667 typ host generation 0
↵a=candidate:1210451609 1 udp 1686052607 118.189.54.34 54667 typ srflx raddr 192.168.1.51 rport 54667 generation 0
↵a=candidate:4038427581 1 tcp 1518280447 192.168.1.51 0 typ host tcptype active generation 0
↵a=ice-ufrag:Go2bBoWAFVSF8R7B
↵a=ice-pwd:u7zcCfcuUv1Z4PSMm6xwoO/b
↵a=fingerprint:sha-256 65:46:C0:16:7B:5D:09:02:AE:E3:6A:BE:A1:80:57:A8:E8:92:6D:D7:A6:ED:DE:3C:3D:DD:7C:8C:FB:6C:04:58
↵a=setup:actpass
↵a=mid:data
↵a=sctpmap:5000 webrtc-datachannel 1024
↵"type: "offer"__proto__: RTCSessionDescription
skylink.complete.js:16417 SkylinkJS - <<Event>> (handshakeProgress) Event is fired
skylink.complete.js:16417 SkylinkJS - <<Event>> (handshakeProgress) Event is triggered
skylink.complete.js:16415 SkylinkJS [HBeWmGbm0MJf3cLRABg_] - (offer) Failed setting remote description: Failed to set remote offer sdp: Called in wrong state: STATE_SENTOFFER
```

**Comment by letchoo** [comment]
@tienthanh8490 Thanks. Looks like at some states when I am sending offer, I am receiving offer. Okay this proves that two peers doing the restart at the same time has issues. To figure a solution. Any ideas?

**Comment by tienthanh8490** [comment]
Your offer will be relayed by signaling so better check if you give it the correct target.
I didn't do simultaneous restart though, only one sided

**Comment by letchoo** [comment]
@tienthanh8490 Ok I could reproduce this now. I'll take a look. Thanks.

**Comment by letchoo** [comment]
@tienthanh8490 as you have suggested before, I think we need to add flags to prevent stimeuousl restarts. The restart timer expired hence triggering the restart connection

**Comment by letchoo** [comment]
@tienthanh8490, please consider to try again. However there is an issue where if both creates the offer at the same time, both peers connection state would be at `"have-local-offer"`, which would cause an error to set an offer at the same time.

**Comment by letchoo** [comment]
@tienthanh8490 I've updated the code base.

__Things to note:__
- Removed `_peerRestartPriorities` with a fixed generated weight for restart mechanism `_peerRestartWeight`.
- Upon calling `_restartPeerConnection` first, it will not do the restart instantly but send the restart message where it will be checked against by the other peer, if not it sends the _WELCOME_ message to let the other peer do the offer (same logic as the `_doOffer` if `beOfferer === false`.

This mechanism made the offer more stable so far.

**Comment by letchoo** [comment]
Note that I have tested 0.6.5 for trickleICE = false and it seems like the results is the same.

So it's likely that the new re-negotiation method did not affect it in any way.

**Comment by letchoo** [comment]
Another concern which is related to what @tienthanh8490 brought up, what if the peers are exchanging O/A because there is no connection establishment yet and then restart happens.

To look into it this trap logic.

**Comment by agouaillard** [comment]
guys,

the "simultaneous offer/restart/....' is called "glare" in the RTC world.

The usual way of dealing with it without adding complexity is to
arbitrarily decide that one peer has higher priority, depending on the
peerID, say the highest always win. You can ask sherwin for smarter ways,
or google it, but what you should try to do is NOT to add more flags.

HTH

On Thu, Dec 17, 2015 at 6:49 AM, Leticia Choo <notifications@github.com>
wrote:

> Another concern which is related to what @tienthanh8490
> <https://github.com/tienthanh8490> brought up, what if the peers are
> exchanging O/A because there is no connection establishment yet and then
> restart happens.
>
> To look into it this trap logic.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Temasys/SkylinkJS/pull/168#issuecomment-165347692>.
>



-- 
Alex. Gouaillard, PhD, PhD, MBA
------------------------------------------------------------------------------------
Principal Architect - Citrix, San Francisco
President - CoSMo Software Consulting, Singapore
------------------------------------------------------------------------------------
sg.linkedin.com/agouaillard

   -

**Comment by ncurrier** [comment]
@tienthanh8490 @letchoo please use the solution that was discussed yesterday for this. @tienthanh8490 as you are aware this will require a small modification to the signaling

**Pull request merged**
