### PR TITLE
Implement Safari 11 support

### PR DESCRIPTION
**Pull request by oooookk7**
Updated PR of #292, this is the cleaned up version of that PR so that the commits are easier to be read and the changes can be minimal and reviewed again for release.

**Updates:**

- Parse correct MediaStream IDs to be returned to end-user.
- Handle case where newly created datachannel after offer / answer negotiation that wouldn't open, so added a new flag `enableSimultaneousTransfers` (default : `true`) so users can disable it for Safari 11 case and send blobs to other browsers on the same datachannel they used to create before offer was created.
- Refactored `getStats()` rendering to ensure that correct stats are reflected correctly.
  - Ensure that remote and local ICE candidates are returned correctly.
  - Handle `getStats()` with Promises.
  - Handle Safari 11 stats. Added workaround to determine the selected candidate pair based on the computed priority as per [RFC 5245](https://tools.ietf.org/html/rfc5245).
  - Ensure that remote and local SSRCs are returned correctly.
  - Make sure that audio & video sending and receiving returns `0` for "bytes", "totalBytes", "packets" and "totalPackets" if undefined for Safari 11 and Edge 15.
- Cleaned up code to move error & success callbacks to a separate function.
- Removed ".src" use for demo/app.
- Removed `_isUsingPlugin` references.
- Handle Firefox 53 TURNs support [as resolved here](https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1056934).
- Handle Safari 11 ".oniceconnectionstatechange" and ".onsignalingstatechange" CLOSED state by triggering event state when `RTCPeerConnection.close()` is invoked.
- Removed references of `window.webrtc...` to `AdapterJS.webrtc...`.
- Handle case where H264 is not supported with e.g. Temasys WebRTC version `0.8.869` for audio connections.

### CODE REVIEW

**Comment by johache** [comment]
Added 1 comment (no screenshare on Safari 11)

Could you also add support for AdapterJS.options.forceSafariPlugin ?
That overrides the Safari 11 APIs in favour of the plugin's.

**Comment by oooookk7** [comment]
As discussed with @ncurrier, we will document how they can do the flag overrides since it would be the better way forward.

**Comment by oooookk7** [comment]
@johache added the documentation in README.md. As for the screensharing, <s>`getUserMedia()` should reject the request so `shareScreen()` will fail.</s> to prevent limiting such functionality I'll just let Safari reject screensharing, unless you think it's better we reject it in the SDK.

**Review by johache — APPROVED** [review]
LGTM

**Pull request merged**
